defaults:
    -
        scope:
            path: ''
            collection: 'knowledge'

exclude:
    - 'Gemfile'
    - 'LICENSE'
    - 'README.md'

collections:
    knowledge:
        output: true
        output_ext: html
        permalink: /:path/

fb-group-id: 2204685680

gems:
    - 'jekyll-redirect-from'
